# Generated by Django 3.1.3 on 2021-11-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211124_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrydata',
            old_name='contry',
            new_name='country',
        ),
    ]
